### PR TITLE
Fix imported exceptions

### LINKED ISSUE #31: Exception name change in Codecetption
ModuleConfig was changed to ModuleConfigException in v2.1.0

> PHP Fatal error:  Uncaught Error: Class 'Codeception\Exception\ModuleConfig' not found in vendor/codeception/phpbuiltinserver/src/Codeception/Extension/PhpBuiltinServer.php:119

### PR DESCRIPTION
**Pull request by mbrodala**
The old exception classes do not exist anymore in newer CodeCeption releases.

Fixes #31

### CODE REVIEW

**Comment by davidjeddy** [comment]
@mbrodala any chance we can get a corrected patch?

**Comment by mbrodala** [comment]
> PhpBrowser: Guzzle is not installed. Please install `guzzlehttp/guzzle` with composer

This is odd since that package is installed during build... I'll drop the `--prefer-lowest` from my change for now, but this should be added in a separate one.

**Comment by mbrodala** [comment]
OK, I think this should do.

**Comment by conorgahan** [comment]
Hi,

Is there any chance of getting this pull request merged as the bug it fixes has me blocked on the latest version of Codeception?

Thanks!

**Comment by mbrodala** [comment]
@conorgahan Until then you add the following to your `composer.json` and require `cweagans/composer-patches`:

```json
  "extra": {
    "patches": {
      "codeception/phpbuiltinserver": {
        "Fix imported exceptions": "https://github.com/mbrodala/PhpBuiltinServer/commit/3bfce63597fd5187154b0b1e7ebb9d34084a2e23.patch"
      }
    }
  }
```

**Comment by conorgahan** [comment]
@mbrodala That's great, thanks. I had actually just referenced your fork, but this is a cleaner solution in the short term.

**Comment by mbrodala** [comment]
@tiger-seo Thanks for merging!

**Comment by mbrodala** [comment]
I'll keep my branch alive for now to not break existing references.

**Comment by conorgahan** [comment]
@tiger-seo Thanks for that - is there a release planned or should we just work off dev-master?

@mbrodala Thanks!

**Comment by tiger-seo** [comment]
@conorgahan yeah, i gonna tag this ;)

**Comment by mbrodala** [comment]
@tiger-seo Thanks for the release. :-)

**Comment by conorgahan** [comment]
@tiger-seo Thanks!

**Pull request merged**
