### PR TITLE
Fix: Not stopped server

### PR DESCRIPTION
**Pull request by jelhan**
On linux php built in server was not terminated. proc_open has started two processes. The child process which realy runs php built in server was not terminated.
Fixed as suggested on php.net: http://www.php.net/manual/en/function.proc-get-status.php#93382

### CODE REVIEW

**Comment by neoascetic** [comment]
+1

**Comment by tiger-seo** [comment]
hi
am I wrong or this actually breaks running on windows ?

**Comment by jelhan** [comment]
I'm not running PHP under Windows but as far as I know and concerning [docs](http://php.net/manual/en/function.exec.php) there isn't any problem calling exec() on Windows.

**Comment by tiger-seo** [comment]
@jelhan this PR is adding call of exec from shell, not the php's ``exec()``
and windows has no exec by default:
```
C:\>exec
'exec' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by jelhan** [comment]
Ah sorry, you are right. To long ago since I opened this PR. If only linux is affected we could implement a switch by PHP predefined constant `PHP_OS`.

**Comment by tiger-seo** [comment]
closing this, because already fixed in #20

**Pull request closed without merging**
